### ISSUE TITLE
`make frontend` not working on MacOS Sonoma with m1 chip

### ISSUE THREAD

**Issue by bsassoli** [DLBD-Department/BRIO_x_Alkemy#16]
Hi, I tried runnning `make build` -> `make frontend` and I kept getting the following:
`hostname: illegal option -- I
usage: hostname [-f] [-s | -d] [name-of-host]
docker: Error response from daemon: Conflict. The container name "/brio" is already in use by container "omitted". You have to remove (or rename) that container to be able to reuse that name.`
But even removing the container didn't help.

I suspect it might gave to do with [the following] (TLDR blow) :(https://www.reddit.com/r/perl/comments/10p8p39/macos_port_5000_mystery_solved/#:~:text=Recent%20versions%20of%20macOS%20have,AirPlay%2C%22%20it%20says%20here.)

> Recent versions of macOS have a system setting called AirPlay Receiver, under System Settings -> AirDrop and Handoff (v13.2 Ventura). When that setting is enabled, macOS uses an http connection via port 5000 to allow "nearby devices to send video and audio content to your Mac with AirPlay," it says here.

Also I noticed there's no --I option for `hostname`?

**Comment by dlbddepartment** [comment]
Hi @bsassoli , thanks for this. We checked and actually there was a problem due to the MacOS implementation of `hostname`, which is different from the Linux one. We fixed it making the Makefile OS-sensitive, and now it's supporting both MacOS and Linux. You find the patch in the latest release we just published, https://github.com/DLBD-Department/BRIO_x_Alkemy/releases/tag/v1.1.0.
